### PR TITLE
feature/KienTT/t04 search job by title

### PR DESCRIPTION
**Pull request by truongtrungkien0999**
-Link deloy :https://kientt-job-board-t04.surge.sh/
-Note
search by title and show the most correct and approximate jobs.
Add new global variable SEARCH_JOBS. 
After searching list jobs will be updated by title and pagination will do page split.
-Result: search : title 2
image

### CODE REVIEW

**Comment by tyhvb** [comment]
hi @truongtrungkien0999 , you should rebase this branch on the main branch first

**Comment by tyhvb** [comment]
I suggest that we should apply the api with this param for searching like: `mockapi.io/blogs?title=cool%20blog`

**Comment by truongtrungkien0999** [comment]
> kientt-job-board-t04.surge.sh/



> I suggest that we should apply the api with this param for searching like: `mockapi.io/blogs?title=cool%20blog`



> I suggest that we should apply the api with this param for searching like: `mockapi.io/blogs?title=cool%20blog`

-Link deloy :https://kientt-job-board-t04.surge.sh/
-Note: I fix the search api param in the above format and incorporated pagination for the new job listing.
-Result: search : title 1. there are total 13 search results and paginated by param like: mockapi.io/api/job?page=1&limit=10&title=title%201
image

**Comment by tyhvb** [comment]
is the deploy link update to date with new codes ? i think there is a bug when the page 1 is displaying all 13 results, 
each page should display 10 results per page

**Comment by truongtrungkien0999** [comment]
> is the deploy link update to date with new codes ? i think there is a bug when the page 1 is displaying all 13 results, each page should display 10 results per page

i fix display 10 results per page. please check it again

**Comment by truongtrungkien0999** [comment]
> > is the deploy link update to date with new codes ? i think there is a bug when the page 1 is displaying all 13 results, each page should display 10 results per page
> 
> i fix display 10 results per page. please check it again

i fix t04 done. please check it again. thanks.

**Pull request merged**
